
services:
  # MongoDB Database
  # database:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"

  # Backend Node.js App
  backend:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: unless-stopped



