export const USE_CASE_TOKENS = {
  CreateCouponUseCase: "ICreateCouponUseCase",
  FindAllCouponsUseCase: "IFindAllCouponsUseCase",
  MakeCouponInactiveUseCase: "IMakeCouponInactiveUseCase",
  CouponshowInBanner: "ICouponshowInBannerUseCase",
  FindFeaturedCouponsUseCase: "IFindFeaturedCouponsUseCase",
  ApplyCouponToBookingUseCase: "IApplyCouponToBookingUseCase",
  RemoveCouponToBookingUseCase: "IRemoveCouponToBookingUseCase",
  GetWalletUseCase: "IGetWalletUseCase",
  WithdrawPaymentUseCase: "IWithdrawPaymentUseCase",
  conformWithdrawPaymentUseCase: "IConformWithdrawPaymentUseCase",
  GetAllProvidersWallets: "IGetAllProvidersWallets",
  GetProviderWalletByIdUseCase: "IGetProviderWalletUseCase",
  WithdrawFromProviderWalletUseCase: "IWithdrawFromProviderWalletUseCase",
  GetSubscriptionPlansUseCase: "IGetSubscriptionPlansUseCase",
  CreatePaymentSubscriptionOrderUseCase:
    "ICreatePaymentSubscriptionOrderUseCase",
  VerifySubscriptionPaymentUseCase: "IVerifySubscriptionPaymentUseCase",
  CreateAiChatUseCase: "ICreateAiChatUseCase",
  GetAIChatByIdUseCase: "IGetAIChatByIdUseCase",
  GetProviderAIChatsUseCase: "IGetProviderAIChatsUseCase",
  ManageServiceProviderSubscriptionsUseCase:
    "IManageServiceProviderSubscriptionsUseCase",
  GetAllSubscriptionPlansUseCase: "IGetAllSubscriptionPlansUseCase",
  CreateSubscriptionPlanUseCase: "ICreateSubscriptionPlanUseCase",
  UpdateSubscriptionPlanUseCase: "IUpdateSubscriptionPlanUseCase",
  GetProviderAdsUseCase: "IGetProviderAdsUseCase",
  EditAdUseCase: "IEditAdUseCase",
  CreateAdUseCase: "ICreateAdUseCase",
  GetServiceNamesUseCase: "IGetServiceNamesUseCase",
  AdminGetAdsUseCase: "IAdminGetAdsUseCase",
  ChangeAdStatusUseCase: "IChangeAdStatusUseCase",
  RecommendAdsUseCase: "IRecommendAdsUseCase",
  ExpireAdsUseCase: "IExpireAdsUseCase",
  IncreaseAdClicksUseCase: "IIncreaseAdClicksUseCase",
  UpdateBookingStatusUseCase: "IUpdateBookingStatusUseCase",
  ConfirmBookingUseCase: "IConfirmBookingUseCase",
  CancelBookingUseCase: "ICancelBookingUseCase",
  RequestPaymentUseCase: "IRequestPaymentUseCase",
  CreateBookingUseCase: "ICreateBookingUseCase",
  CreateOnlineBookingUseCase: "ICreateOnlineBookingUseCase",
  GetBookedServicesUseCase: "IGetBookedServicesUseCase",
  GetBookedServiceByIdUseCase: "IGetBookedServiceByIdUseCase",
  CleanupSlotsBeforeTodayUseCase: "ICleanupSlotsBeforeTodayUseCase",
  MarkSlotAsBookedUseCase: "IMarkSlotAsBookedUseCase",
  GetSlotUseCase: "IGetSlotUseCase",
  DeleteSlotUseCase: "IDeleteSlotUseCase",
  CreateSlotUseCase: "ICreateSlotUseCase",
  RescheduleOnlineServiceSlotUseCase: "IRescheduleOnlineServiceSlotUseCase",
  GetServiceProviderRegistrationDetailsUseCase:
    "IGetServiceProviderRegistrationDetailsUseCase",
  GetServiceProviderStatusUseCase: "IGetServiceProviderStatusUseCase",
  ReapplyServiceProviderUseCase: "IReapplyServiceProviderUseCase",
  AddCategory: "IAddCategory",
  AddService: "IAddService",
  BlockUnblockCategory: "IBlockUnblockCategory",
  DeleteService: "IDeleteService",
  BlockUnblockCategoryService: "IBlockUnblockCategoryService",
  EditCategory: "IEditCategory",
  GetCategory: "IGetCategory",
  IBlockUnblockService: "IBlockUnblockService",
  DeleteCategory: "IDeleteCategory",
  BlockUnblockService: "IBlockUnblockService",
  GetAllServices: "IGetAllServices",
};

export const REPOSITORY_TOKENS = {
  ServiceRepository: "ServiceRepository",
  WalletRepository: "IWalletRepository",
  CouponRepository: "ICouponRepository",
  SubscriptionRepository: "ISubscriptionPlanRepository",
  AiAssistanceRepository: "IAiAssistanceRepository",
  ServiceProviderRepository: "IServiceProviderRepository",
  AdRepository: "IAdRepository",
  SlotRepository: "ISlotRepository",
  ServiceBookingRepository: "IServiceBookingRepository",
  UserRepository: "IUserRepository",
  CategoryRepository: "ICategoryRepository",
};
export const SERVICE_TOKENS = {
  MailService: "IMailService",
  GoogleGenAIService: "IGoogleGenAIService",
  CloudinaryService: "ICloudinaryService",
  TokenService: "ITokenService",
  RedisService: "IRedisService",
  RazorpayService: "RazorpayService",
  SmsOtpService: "ISmsOtpService",
  Otpservice: "IOtpservice",
  EmailService: "IEmailService",
  ServiceRepository: "ServiceRepository",
};
