export const USE_CASE_TOKENS = {
  CreateCouponUseCase: "ICreateCouponUseCase",
  FindAllCouponsUseCase: "IFindAllCouponsUseCase",
  MakeCouponInactiveUseCase: "IMakeCouponInactiveUseCase",
  CouponshowInBanner: "ICouponshowInBannerUseCase",
  FindFeaturedCouponsUseCase: "IFindFeaturedCouponsUseCase",
  ApplyCouponToBookingUseCase: "IApplyCouponToBookingUseCase",
  RemoveCouponToBookingUseCase: "IRemoveCouponToBookingUseCase",
  GetWalletUseCase: "IGetWalletUseCase",
  WithdrawPaymentUseCase: "IWithdrawPaymentUseCase",
  conformWithdrawPaymentUseCase: "IConformWithdrawPaymentUseCase",
  GetAllProvidersWallets: "IGetAllProvidersWallets",
  GetProviderWalletByIdUseCase: "IGetProviderWalletUseCase",
  WithdrawFromProviderWalletUseCase: "IWithdrawFromProviderWalletUseCase",
  GetSubscriptionPlansUseCase: "IGetSubscriptionPlansUseCase",
  CreatePaymentSubscriptionOrderUseCase:
    "ICreatePaymentSubscriptionOrderUseCase",
  VerifySubscriptionPaymentUseCase: "IVerifySubscriptionPaymentUseCase",
  CreateAiChatUseCase: "ICreateAiChatUseCase",
  GetAIChatByIdUseCase: "IGetAIChatByIdUseCase",
  GetProviderAIChatsUseCase: "IGetProviderAIChatsUseCase",
  ManageServiceProviderSubscriptionsUseCase:
    "IManageServiceProviderSubscriptionsUseCase",
  GetAllSubscriptionPlansUseCase: "IGetAllSubscriptionPlansUseCase",
  CreateSubscriptionPlanUseCase: "ICreateSubscriptionPlanUseCase",
  UpdateSubscriptionPlanUseCase: "IUpdateSubscriptionPlanUseCase",
  GetProviderAdsUseCase: "IGetProviderAdsUseCase",
  EditAdUseCase: "IEditAdUseCase",
  CreateAdUseCase: "ICreateAdUseCase",
  GetServiceNamesUseCase: "IGetServiceNamesUseCase",
  AdminGetAdsUseCase: "IAdminGetAdsUseCase",
  ChangeAdStatusUseCase: "IChangeAdStatusUseCase",
  RecommendAdsUseCase: "IRecommendAdsUseCase",
  ExpireAdsUseCase: "IExpireAdsUseCase",
  IncreaseAdClicksUseCase: "IIncreaseAdClicksUseCase",
  UpdateBookingStatusUseCase: "UpdateBookingStatusUseCase",
  ConfirmBookingUseCase: "IConfirmBookingUseCase",
  CancelBookingUseCase: "ICancelBookingUseCase",
  RequestPaymentUseCase: "IRequestPaymentUseCase",
  CreateBookingUseCase: "ICreateBookingUseCase",
  CreateOnlineBookingUseCase: "ICreateOnlineBookingUseCase",
  GetBookedServicesUseCase: "IGetBookedServicesUseCase",
  GetBookedServiceByIdUseCase: "IGetBookedServiceByIdUseCase",
  CleanupSlotsBeforeTodayUseCase: "ICleanupSlotsBeforeTodayUseCase",
  MarkSlotAsBookedUseCase: "IMarkSlotAsBookedUseCase",
  GetSlotUseCase: "IGetSlotUseCase",
  DeleteSlotUseCase: "IDeleteSlotUseCase",
  CreateSlotUseCase: "ICreateSlotUseCase",
  RescheduleOnlineServiceSlotUseCase: "IRescheduleOnlineServiceSlotUseCase",
  GetServiceProviderRegistrationDetailsUseCase:
    "IGetServiceProviderRegistrationDetailsUseCase",
  GetServiceProviderStatusUseCase: "IGetServiceProviderStatusUseCase",
  ReapplyServiceProviderUseCase: "IReapplyServiceProviderUseCase",
  AddCategory: "IAddCategory",
  AddService: "IAddService",
  BlockUnblockCategory: "IBlockUnblockCategory",
  DeleteService: "IDeleteService",
  BlockUnblockCategoryService: "IBlockUnblockCategoryService",
  EditCategory: "IEditCategory",
  GetCategory: "IGetCategory",
  BlockUnblockService: "IBlockUnblockService",
  DeleteCategory: "IDeleteCategory",
  GetAllServices: "IGetAllServices",
  GetAllUsers: "IGetAllUsers",
  BlockUnblockUsers: "IBlockUnblockUsers",
  GetServiceProviders: "IGetServiceProviders",
  BlockUnblockSericeProvider: "IBlockUnblockSericeProvider",
  SaveMessageUseCase: "ISaveMessageUseCase",
  GetAllChatsUseCase: "IGetAllChatsUseCase",
  UploadChatImageUseCase: "IUploadChatImageUseCase",
  AdminSignin: "IAdminSignin",
  GetNotificationUseCase: "IGetNotificationUseCase",
  CreateNotificationUseCase: "ICreateNotificationUseCase",
  MarkNotificationAsReadUseCase: "IMarkNotificationAsReadUseCase",
  DeleteSingleNotificationUseCase: "IDeleteSingleNotificationUseCase",
  DeleteAllNotificationUseCase: "IDeleteAllNotificationUseCase",
  AddReviewUseCase: "IAddReviewUseCase",
  DeleteAddress: "IDeleteAddress",
  AddNewAddress: "IAddNewAddress",
  EditAddress: "EditAddress",
  GetAddress: "IGetAddress",
  ResetPasswordUseCase: "IResetPasswordUseCase",
  SendForgotPasswordOtpUseCase: "ISendForgotPasswordOtpUseCase",
  VerifyForgotPasswordOtpUseCase: "IVerifyForgotPasswordOtpUseCase",
  GoogleAuthUseCase: "IGoogleAuthUseCase",
  ResendOtpUseCase: "IResendOtp",
  SignInUseCase: "ISignInUseCase",
  SignUpUseCase: "ISignUpUseCase",
  VerifyOtpUseCase: "IVerifyOtpUseCase",
  GetServiceProviderInfoUseCase: "GetServiceProviderInfoUseCase",
  GetAllActiveServiceUseCase: "GetAllActiveServiceUseCase",
  GetSingleServiceUseCase: "GetSingleServiceUseCase",
  ProfileUpdateOtpUseCase: "ProfileUpdateOtpUseCase",
  UserProfileUpdateUseCase: "IUserProfileUpdateUseCase",
  GetUserProfileUseCase: "IGetUserProfileUseCase",
  CreateServiceOrderUseCase: "CreateServiceOrderUseCase",
  FindAllActiveCouponsUseCase: "IFindAllActiveCouponsUseCase",
};

export const REPOSITORY_TOKENS = {
  ServiceRepository: "ServiceRepository",
  WalletRepository: "IWalletRepository",
  CouponRepository: "ICouponRepository",
  SubscriptionRepository: "ISubscriptionPlanRepository",
  AiAssistanceRepository: "IAiAssistanceRepository",
  ServiceProviderRepository: "IServiceProviderRepository",
  AdRepository: "IAdRepository",
  SlotRepository: "ISlotRepository",
  ServiceBookingRepository: "IServiceBookingRepository",
  UserRepository: "IUserRepository",
  CategoryRepository: "ICategoryRepository",
  ChatRepository: "ChatRepository",
  NotificationRepository: "NotificationRepository",
  ReviewRepository: "ReviewRepository",
};
export const SERVICE_TOKENS = {
  MailService: "IMailService",
  GoogleGenAIService: "IGoogleGenAIService",
  CloudinaryService: "ICloudinaryService",
  TokenService: "ITokenService",
  RedisService: "IRedisService",
  RazorpayService: "RazorpayService",
  SmsOtpService: "ISmsOtpService",
  EmailService: "IEmailService",
  ServiceRepository: "ServiceRepository",
  OtpService: "IOtpService",
};

// IBlockUnblockUsers
// BlockUnblockSericeProvider
// IGetServiceProviders
// IServiceProviderRejectVerify
